<a href="https://colab.research.google.com/github/PradeepK-eng/Google-Colab-Files/blob/main/Pratice_1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy will takes less moemmory:

In [ ]:
import numpy as np
import time
import sys

I = range(1000)
print(sys.getsizeof(1)*len(I))

array = np.arange(1000)
print(array.size*array.itemsize)

28000
8000


numpy is fast and convient to andle rather than python list for handling a large data!


In [ ]:
size = 10000000

l1 = range(size)
l2 = range(size)

a1 = np.arange(size)
a2 = np.arange(size)

#python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Python list took:", (time.time()-start)*1000)

#numpy array
start = time.time()
result = a1+a2
print("Numpy array took:", (time.time()-start)*1000)


Python list took: 2079.341411590576
Numpy array took: 430.59253692626953


In [ ]:
a = np.array([1,2,3,4,5])
print(a.ndim)
print(a.itemsize)
b = np.array([1,2,3,4,5], dtype=np.float64)
print(b.itemsize)
b


1
8
8


array([1., 2., 3., 4., 5.])

In [ ]:
c = np.array([[1,2],[3,4],[5,6]])
#c
print(a.shape)
print(a.size)
print(c.shape)
print(c.size)


(5,)
5
(3, 2)
6


In [ ]:
d=np.ones((2,2))
e=np.zeros((3,3))
f=np.arange(1,5,2)
g=np.linspace(0,50,5)
print(g)
f=np.linspace(1,50,5)
print(f)
h=np.linspace(0,50,6)
print(h)
b = a.reshape(5,1)
print(b)
#print(b.shape)
#b = a.reshape(1,5)
#print(b)
#print(c)
#print(c.ravel())

[ 0.  12.5 25.  37.5 50. ]
[ 1.   13.25 25.5  37.75 50.  ]
[ 0. 10. 20. 30. 40. 50.]


ValueError: cannot reshape array of size 4 into shape (5,1)

In [ ]:
c
print("Minimum elemt is: ", c.min())
print("Max elemt is : ", c.max())
print("Total sum of elements is: ", (c.sum()))
print("sum in coloumn wise array :", c.sum(axis=0))
print("sum in row wise array :", c.sum(axis=1))

Minimum elemt is:  1
Max elemt is :  6
Total sum of elements is:  21
sum in coloumn wise array : [ 9 12]
sum in row wise array : [ 3  7 11]


In [ ]:
a
z= np.sqrt(a)
print(z)
np.std(a)

[1.         1.41421356 1.73205081 2.         2.23606798]


np.float64(1.4142135623730951)

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(b/a)
print(a.dot(b))
print(b.dot(a))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[5.         3.        ]
 [2.33333333 2.        ]]
[[19 22]
 [43 50]]
[[23 34]
 [31 46]]
